apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "activemq.fullname" . }}
  labels:
    app: {{ template "activemq.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "activemq.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: activemq
        image: "{{ .Values.activemq.image.repository }}:{{ .Values.activemq.image.tag }}"
        imagePullPolicy: {{ .Values.activemq.image.pullPolicy }}
        env:
        - name: ACTIVEMQ_CONFIG_MINMEMORY
          value: "{{ .Values.activemq.image.configMinMemory }}"
        - name: ACTIVEMQ_CONFIG_MAXMEMORY
          value: "{{ .Values.activemq.image.configMaxMemory }}"
        - name: ACTIVEMQ_BROKER_NAME
          value: "{{ .Values.activemq.image.configBrokerName }}"
        - name: ACTIVEMQ_ADMIN_LOGIN
          value: "{{ .Values.activemq.image.configAdminLogin }}"
        - name: ACTIVEMQ_ADMIN_PASSWORD	
          value: "{{ .Values.activemq.image.configAdminPassword }}"
        ports:
        - name: stomp
          containerPort: {{ .Values.activemq.services.broker.ports.internal.stomp | default 61613 }}
        - name: openwire
          containerPort: {{ .Values.activemq.services.broker.ports.internal.openwire | default 61616 }}
        - name: amqp
          containerPort: {{ .Values.activemq.services.broker.ports.internal.amqp | default 5672 }}
        - name: web-console
          containerPort: {{ .Values.activemq.services.webConsole.ports.internal.webConsole | default 8161 }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.activemq.services.broker.ports.internal.openwire | default 61616 }}
          initialDelaySeconds: {{ .Values.activemq.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.activemq.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.activemq.readinessProbe.failureThreshold }}
          timeoutSeconds: {{ .Values.activemq.readinessProbe.timeoutSeconds }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.activemq.services.broker.ports.internal.openwire | default 61616 }}
          initialDelaySeconds: {{ .Values.activemq.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.activemq.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.activemq.livenessProbe.failureThreshold }}
          timeoutSeconds: {{ .Values.activemq.livenessProbe.timeoutSeconds }}
        volumeMounts:
        - name: data
          mountPath: {{ .Values.persistence.mountPath }}
          subPath: {{ .Values.persistence.subPath }}
        resources:
{{ toYaml .Values.activemq.resources | indent 12 }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim }}