image:
  repository: alfresco/alfresco-activemq
  tag: 5.15.6-java-8-oracle-centos-7-ac5b98b35cd4
  pullPolicy: Always
  configMinMemory: "512"
  configMaxMemory: "2048"
  configBrokerName : activemq-broker
  configAdminLogin: admin
  configAdminPassword: admin
resources:
  requests:
    memory: "512Mi"
  limits:
    memory: "2048Mi"
services:
  broker:
    ports:
      internal:
        stomp: 61613
        amqp: 5672
        openwire: 61616
      external:
        stomp: 61613
        amqp: 5672
        openwire: 61616      
    name: "{{ .Values.image.configBrokerName }}"
    type: ClusterIP
  webConsole:
    ports:
      internal:
        webConsole: 8161
      external:
        webConsole: 8161
    name: activemq-web-console
    type: NodePort
# The ActiveMQ readiness probe is used to check startup only as a failure
# of the liveness probe later will result in the pod being restarted.
readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 20
  timeoutSeconds: 10
  failureThreshold: 6
livenessProbe:
  initialDelaySeconds: 130
  periodSeconds: 20
  timeoutSeconds: 10
  failureThreshold: 1

persistence:
  existingClaim: "alfresco-volume-claim"
  mountPath: "/data"
  subPath: "alfresco-infrastructure/activemq-data"